version: '2.2'

services:
    redis:
        mem_limit: 256m
        cpus: 0.25
        restart: always
        image: jbuncle/onetimesecret-redis-docker
        environment:
            REDIS_PASSWORD: $REDIS_PASSWORD
        logging:
            driver: json-file
            options:
               max-size: "100m"
           
    onetimesecret:
        mem_limit: 512m
        cpus: 1
        depends_on:
          - redis
        image: jbuncle/onetimesecret-docker
#        build: .
        restart: always
        networks:
            - shared
            - default
        dns:
            - "8.8.8.8"
        environment:
           DEFAULT_HOST: $HOSTNAME
           VIRTUAL_HOST: $HOSTNAME
           EXTERNAL_HOST: $HOSTNAME
           REDIS_HOST: redis
           REDIS_PASSWORD: $REDIS_PASSWORD
           SSL: 'false'
        logging:
            driver: json-file
            options:
               max-size: "100m"

networks:
    shared:
        external: true
